SELECT e.mjd_obs,
o.imageid,
y.COADD_OBJECTS_ID,
ms.MQ_ROWNUM,
y.RA,
y.DEC,
o.mag_psf+i.zeropoint as mag_psf,
o.magerr_psf+i.sigma_zeropoint as magerr_psf,
o.band,
i.exptime,
e.id as exposureid,
t.tag as exposuretag,
o.mag_auto+i.zeropoint as mag_auto,
o.magerr_auto+i.sigma_zeropoint as magerr_auto,
o.mag_iso+i.zeropoint as mag_iso,
o.magerr_iso+i.sigma_zeropoint as magerr_iso,
o.mag_aper_1+i.zeropoint as mag_aper_1,
o.magerr_aper_1+i.sigma_zeropoint as magerr_aper_1,
o.mag_aper_2+i.zeropoint as mag_aper_2,
o.magerr_aper_2+i.sigma_zeropoint as magerr_aper_2,
o.mag_aper_3+i.zeropoint as mag_aper_3,
o.magerr_aper_3+i.sigma_zeropoint as magerr_aper_3,
o.mag_aper_4+i.zeropoint as mag_aper_4,
o.magerr_aper_4+i.sigma_zeropoint as magerr_aper_4,
o.mag_aper_5+i.zeropoint as mag_aper_5,
o.magerr_aper_5+i.sigma_zeropoint as magerr_aper_5,
o.mag_aper_6+i.zeropoint as mag_aper_6,
o.magerr_aper_6+i.sigma_zeropoint as magerr_aper_6,
o.mag_aper_7+i.zeropoint as mag_aper_7,
o.magerr_aper_7+i.sigma_zeropoint as magerr_aper_7,
o.mag_aper_8+i.zeropoint as mag_aper_8,
o.magerr_aper_8+i.sigma_zeropoint as magerr_aper_8,
o.mag_aper_9+i.zeropoint as mag_aper_9,
o.magerr_aper_9+i.sigma_zeropoint as magerr_aper_9,
o.mag_aper_10+i.zeropoint as mag_aper_10,
o.magerr_aper_10+i.sigma_zeropoint as magerr_aper_10,
o.mag_aper_11+i.zeropoint as mag_aper_11,
o.magerr_aper_11+i.sigma_zeropoint as magerr_aper_11,
o.mag_aper_12+i.zeropoint as mag_aper_12,
o.magerr_aper_12+i.sigma_zeropoint as magerr_aper_12
FROM des_admin.Y1A1_COADD_OBJECTS y, des_admin.y1a1_objects o, des_admin.y1a1_image i,des_admin.y1a1_exposure e,rumbaugh.milliquas_y1a1_match ms, des_admin.Y1A1_EXPOSURETAG t
where o.imageid=i.id 
and i.exposureid=e.id 
and t.exposureid=e.id
and ms.coadd_objects_id=y.coadd_objects_id 
and y.coadd_objects_id=o.coadd_objects_id; > milliquas_lightcurve_entries_y1a1.tab
