SELECT r.COADD_OBJECTS_ID,y.MAG_PSF_Y,y.MAG_PSF_G,y.MAG_PSF_R,y.MAG_PSF_I,y.MAG_PSF_Z
FROM DES_ADMIN.Y1A1_COADD_OBJECTS y, RUMBAUGH.SDSSPOSS_Y1A1_MATCH r
where y.COADD_OBJECTS_ID=r.COADD_OBJECTS_ID; >sdssposs_y1a1_coadd_mags.tab
