execfile("FindCloseSources.py")

names = np.array(['548','4161','0849'])
path = '/home/rumbaugh/LFC'

for i in range(0,3):
    FILE = open('%s/%s/opt_match/mask_list.%s.dat'%(path,names[i],names[i]),"w")
    cr = read_file('%s/%s/opt_match/opt_Xray_matched_catalog_3high.twk.dat'%(path,names[i]))
    raX = get_colvals(cr,'col2')
    decX = get_colvals(cr,'col3')
    nm = get_colvals(cr,'col5')
    raopt1 = get_colvals(cr,'col6')
    decopt1 = get_colvals(cr,'col7')
    idopt1 = get_colvals(cr,'col8')
    raopt2 = get_colvals(cr,'col11')
    decopt2 = get_colvals(cr,'col12')
    idopt2 = get_colvals(cr,'col13')
    raopt3 = get_colvals(cr,'col16')
    decopt3 = get_colvals(cr,'col17')
    idopt3 = get_colvals(cr,'col18')
    for j in range(0,len(nm)):
        if nm[j] > 0.1: FILE.write('%6i %10.5f %9.5f %10.5f %9.5f\n'%(int(idopt1[j]),raopt1[j],decopt1[j],raX[j],decX[j]))
        if nm[j] > 1.1: FILE.write('%6i %10.5f %9.5f %10.5f %9.5f\n'%(int(idopt2[j]),raopt2[j],decopt2[j],raX[j],decX[j]))
        if nm[j] > 2.1: FILE.write('%6i %10.5f %9.5f %10.5f %9.5f\n'%(int(idopt3[j]),raopt3[j],decopt3[j],raX[j],decX[j]))
    cr2 = read_file('%s/%s/opt_match/opt_Xray_matched_catalog_3high.twk.dat.minsrch.dat'%(path,names[i]))
    raX2 = get_colvals(cr,'col2')
    decX2 = get_colvals(cr,'col3')
    nm2 = get_colvals(cr,'col5')
    raopt12 = get_colvals(cr,'col6')
    decopt12 = get_colvals(cr,'col7')
    idopt12 = get_colvals(cr,'col8')
    raopt22 = get_colvals(cr,'col11')
    decopt22 = get_colvals(cr,'col12')
    idopt22 = get_colvals(cr,'col13')
    raopt32 = get_colvals(cr,'col16')
    decopt32 = get_colvals(cr,'col17')
    idopt32 = get_colvals(cr,'col18')
    g = np.where(nm2 > nm)
    g = g[0]
    for j in range(0,len(g)):
        if ((nm2[j] > 0.1) and (idopt12[j] != idopt1[j]) and (idopt12[j] != idopt2[j]) and (idopt12[j] != idopt3[j])): FILE.write('%6i %10.5f %9.5f %10.5f %9.5f\n'%(int(idopt12[j]),raopt12[j],decopt12[j],raX2[j],decX2[j]))
        if ((nm2[j] > 1.1) and (idopt22[j] != idopt1[j]) and (idopt22[j] != idopt2[j]) and (idopt22[j] != idopt3[j])): FILE.write('%6i %10.5f %9.5f %10.5f %9.5f\n'%(int(idopt22[j]),raopt22[j],decopt22[j],raX2[j],decX2[j]))
        if ((nm2[j] > 2.1) and (idopt32[j] != idopt1[j]) and (idopt32[j] != idopt2[j]) and (idopt32[j] != idopt3[j])): FILE.write('%6i %10.5f %9.5f %10.5f %9.5f\n'%(int(idopt32[j]),raopt32[j],decopt32[j],raX2[j],decX2[j]))
    FILE.close()
