SELECT
CO.COADD_OBJECTS_ID,
CO.RA, CO.DEC,
CO.MAG_AUTO_G, CO.MAG_AUTO_R, CO.MAG_AUTO_I, CO.MAG_AUTO_Z, CO.MAG_AUTO_Y, 
CO.MAGERR_AUTO_G, CO.MAGERR_AUTO_R, CO.MAGERR_AUTO_I, CO.MAGERR_AUTO_Z, CO.MAGERR_AUTO_Y
FROM 
des_admin.Y1A1_COADD_OBJECTS CO
WHERE 
CO.MAG_AUTO_G - CO.MAG_AUTO_R < 0.6 AND
CO.MAG_AUTO_R - CO.MAG_AUTO_I < 0.45 AND
CO.MAG_AUTO_I - CO.MAG_AUTO_Z < 0.55;
> Y1A1_COADDS_SIMPLE_CUTS_MAG_AUTO.csv
