py.scatter(ltime+0.1,Bflux/np.mean(Bflux),s=20,color='r',label='B')
py.scatter(ltime,Cflux/np.mean(Cflux),s=20,color='b',label='C')
py.legend()
py.errorbar(ltime+0.1,Bflux/np.mean(Bflux),Berr/np.mean(Bflux),linestyle='None',color='r')
py.errorbar(ltime,Cflux/np.mean(Cflux),Cerr/np.mean(Cflux),linestyle='None',color='b')
py.xlim(-5,80)
py.savefig('/home/rumbaugh/B1938+666_files/B1938.BC_light_curves.norm.4.25.13.ps')
py.close()

py.scatter(ltime+45.5,Bflux/np.mean(Bflux)*np.mean(Cflux),s=20,color='r',label='B')
py.scatter(ltime,Cflux,s=20,color='b',label='C')
py.legend()
py.errorbar(ltime+45.5,Bflux/np.mean(Bflux)*np.mean(Cflux),Berr/np.mean(Bflux)*np.mean(Cflux),linestyle='None',color='r')
py.errorbar(ltime,Cflux,Cerr,linestyle='None',color='b')
py.xlim(-5,130)
py.savefig('/home/rumbaugh/B1938+666_files/B1938.BC_light_curves.delay.4.25.13.ps')
py.close()
